
services:
  db:
    image: postgres:15
    env_file:
      - .env  # Correct path if running from project root
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=$POSTGRES_PASSWORD pg_isready -U $POSTGRES_USER -d $POSTGRES_DB -h db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  web:
    build:
      context: ..
      dockerfile: infra/docker/Dockerfile
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: always

volumes:
  pg_data:
